name: Spring Workshops
markdown: kramdown
safe: true
lsi: false
highlighter: rouge
encoding: utf-8
baseurl: http://kospiotr.github.io
permalink: /blog/:year/:month/:day/:title/
kospiotrPageURL: http://kospiotr.github.io/
